name: Run python and greet

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Greet the coder
      uses: ./
      with:
        MY_NAME: "Matej "
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Run python app
      run: |
        python app.py
